In [1]:
import numpy as np

In [9]:
def generate(generations, pool, k):
    firstElement = generations[-1]
    if len(generations) == k:
        print(generations)
    for i in range(firstElement, len(pool)):
        generations.append(pool[i])
        generate(generations, pool, k)
        generations.pop()
def generateCombination(k,n):
    generations = []
    pool = list(range(1,n+1))
    for i in range(0,n):
        generations.append(pool[i])
        generate(generations, pool, k)
        generations.pop()

In [8]:
def test(testList):
    print(testList)

experiment = []
experiment.append(1)
test(experiment)
experiment.pop()
test(experiment)

[1]
[]


In [10]:
generateCombination(3,6)

[1, 2, 3]
[1, 2, 4]
[1, 2, 5]
[1, 2, 6]
[1, 3, 4]
[1, 3, 5]
[1, 3, 6]
[1, 4, 5]
[1, 4, 6]
[1, 5, 6]
[2, 3, 4]
[2, 3, 5]
[2, 3, 6]
[2, 4, 5]
[2, 4, 6]
[2, 5, 6]
[3, 4, 5]
[3, 4, 6]
[3, 5, 6]
[4, 5, 6]


In [15]:
with open('chess.dat', 'r') as file:
    lines = file.readlines()
trimmedLines = []
with open('chessTrimmed.dat', 'w') as file:
    for line in lines:
        trimmedLine = line.strip()
        file.write(trimmedLine)
        file.write('\n')

In [2]:
input = np.loadtxt("chessTrimmed.dat", dtype='i', delimiter=' ')
print(input)
len(input[0])

[[ 1  3  5 ... 70 72 74]
 [ 1  3  5 ... 70 72 74]
 [ 1  3  5 ... 70 72 74]
 ...
 [ 2  4  5 ... 70 73 74]
 [ 2  4  5 ... 71 73 74]
 [ 2  4  5 ... 71 73 74]]


37

In [3]:
print(len(input))
print(len(input[0]))
rows = len(input)
cols = len(input[0])

3196
37


In [4]:
matrix = []
for i in range(0,rows):
    matrix.append([])
    k = 0
    for j in range(1,76):
        if input[i][k] == j:
            matrix[i].append(1)
            if k != 36: 
                k += 1
        else:
            matrix[i].append(0)
print(matrix[0])

[1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]


In [5]:
def getSupport(combination, matrix):
    occurences = 0
    resultAnd = 1
    for row in matrix:
        for i in combination:
            resultAnd *= row[i - 1]
        if(resultAnd == 1):
            occurences += 1
        resultAnd = 1
    return occurences/len(matrix)

def getConfidence(X, Y, matrix):
    united = X + Y
    united.sort()
    return getSupport(united,matrix)/getSupport(X,matrix)

def generate(generations, pool, k, matrix, minSupport = 0.25, minConfidence = 0.5):
    firstElement = generations[-1]
    if len(generations) == k:
        print(generations)
        return False
    support = getSupport(generations, matrix)
    if support <= minSupport:
        #print(f"Generace {generations} měla support {support} a byla breaknuta")
        return False
    for i in range(firstElement, len(pool)):
        generations.append(pool[i])
        generate(generations, pool, k, matrix)
        generations.pop()
        
def generateCombination(k,n, matrix, minSupport = 0.25, minConfidence = 0.5):
    generations = []
    pool = list(range(1,n+1))
    for i in range(0,n):
        generations.append(pool[i])
        generate(generations, pool, k, matrix)
        generations.pop()

In [6]:
getSupport([1, 3, 5], matrix)

0.4305381727158949

In [ ]:
generateCombination(4,75, matrix)
#for i in range(1,6):
    #generateCombination(i,75, matrix)